import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";

import SessionProvider from "../components/SessionProviders";
import NavMenu from "../components/NavMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <main className="mx-auto max-w-7xl flex gap-12 px-5 py-12 min-h-screen">
            <aside className="w-64 flex-shrink-0">
              <NavMenu />
            </aside>

            <section className="flex-1 min-w-[430px]">{children}</section>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
